### ISSUE TITLE
Implement NebraskaCloud References into test scenarios

### ISSUE THREAD

**Issue by bkardell13** [cseseniordesign/know-your-well#229]

**Comment by jacobamisano** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDNqIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--69bdd309cef6b224394937cde126dbbb73fc3462/image.png)
Here is an image for reference of the available properties. To login to the account above, you can go to [this address](https://urldefense.com/v3/__https://idp.nebraskacloud.org/simplesaml/module.php/core/authenticate.php?as=nebraskacloud-auth__;!!PvXuogZ4sRB2p-tU!BPb7NF3SaBChRuTZzTEwDt4Do7sycpC_2QU4nInaGSRZqsl8zQ2f6RH3rbjA6KFssHsQuV0xgr7toMO0rguFBM2EJQ$), select "Grand Bend Test ISD Users" and use kyw-teacher as the username and charisma5210dozens as the password, additionally you can use kyw-student : monarchdecorator2931 for another test user as seen below.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWZqIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e9147aa5804ca955bc397fc007ecb56603b328b6/image.png)

**Comment by jacobamisano** [comment]
Other useful links: 
[.NET SAML Library](https://urldefense.com/v3/__https://www.itfoxtec.com/identitysaml2__;!!PvXuogZ4sRB2p-tU!BPb7NF3SaBChRuTZzTEwDt4Do7sycpC_2QU4nInaGSRZqsl8zQ2f6RH3rbjA6KFssHsQuV0xgr7toMO0rgtP0F1gfQ$)
[Nebraska Cloud Identity Provider (IdP) XML Metadata](https://urldefense.com/v3/__https://idp.nebraskacloud.org/simplesaml/saml2/idp/metadata.php__;!!PvXuogZ4sRB2p-tU!BPb7NF3SaBChRuTZzTEwDt4Do7sycpC_2QU4nInaGSRZqsl8zQ2f6RH3rbjA6KFssHsQuV0xgr7toMO0rgt9eKYbgg$)
