### ISSUE TITLE
Create tooltip text for fields to give the user more info

### ISSUE THREAD

**Issue by bkardell13** [cseseniordesign/know-your-well#244]

**Comment by jacobamisano** [comment]
The Bootstrap is currently in the package-lock.json/package.json and you can use tooltips using the [bootstrap tooltip documentation](https://getbootstrap.com/docs/4.0/components/tooltips/)

an example would be `<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="left" title="Tooltip on left">
  Tooltip on left
</button>` 
(as seen in the documentation linked above)
