### ISSUE TITLE
Create tests for tooltips

### ISSUE THREAD

**Issue by kbreit2** [cseseniordesign/know-your-well#421]

**Comment by kierin-101** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Know-Your-Well-Project-Zenhub-631a0b47ff96b8461cc75bb6/issues/cseseniordesign/know-your-well/421?planning-poker) with Zenhub @kbreit2 @mallami2 @mckclarke @Tre-Vawn
