### ISSUE TITLE
Add automatic upload of offline WellInfo when connection is restored

### ISSUE THREAD

**Issue by kbreit2** [cseseniordesign/know-your-well#422]

**Comment by kierin-101** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Know-Your-Well-Project-Zenhub-631a0b47ff96b8461cc75bb6/issues/cseseniordesign/know-your-well/422?planning-poker) with Zenhub @kbreit2 @mallami2 @mckclarke @Tre-Vawn
